n = input('Digite algo: ')
print('o tipo primitivo desse valor é {}'.format(type(n)))
print('Só tem espaço? {}'.format(n.isspace()))
print('É um número ?' , n.isnumeric())
print('É alfabético ?' , n.isalpha())
print('É alfanúmerico ?' , n.isalnum())
print('Está em maiúsculas ?' , n.isupper())
print('Está em minúsculas ?' , n.islower())
print('Está capitalizada ?' , n.istitle())
